services:
  - type: web
    name: myapp-server
    env: node
    rootDir: server
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false

  - type: web
    name: myapp-client
    env: node
    rootDir: client
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npx serve -s build
    envVars:
      - key: REACT_APP_API_URL
        value: https://myapp-server.onrender.com
